version: "2.4"
services:
  hivemq:
    # image: hivemq/hivemq-ce:latest
     image: hivemq/hivemq4:latest
    mem_limit: 800M
    mem_reservation: 800M
    ports:
    - 1883
    - 8080
    environment:
      JAVA_OPTS: "-XX:+UnlockExperimentalVMOptions -XX:InitialRAMPercentage=30 -XX:MaxRAMPercentage=80 -XX:MinRAMPercentage=30"
    # Wait until HiveMQ is completely started
    healthcheck:
      test: ["CMD", "echo", "\"\"", ">", "/dev/tcp/127.0.0.1/1883"]
      interval: 5s
      timeout: 5s
      retries: 10
 
 
